services:
  postgre:
    image: quay.io/debezium/example-postgres:latest
    container_name: postgre
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dibimbing
    networks:
      - dibimbing

networks:
  dibimbing:
    external: true
